export const ActionType = {
	FETCH_EMPLOYEE_LIST_BEGIN: 'FETCH_EMPLOYEE_LIST_BEGIN',
	FETCH_EMPLOYEE_LIST_SUCCESS: 'FETCH_EMPLOYEE_LIST_SUCCESS',
	FETCH_EMPLOYEE_LIST_FAILED: 'FETCH_EMPLOYEE_LIST_FAILED',
	ADD_EMPLOYEE_LIST_BEGIN: 'ADD_EMPLOYEE_LIST_BEGIN',
	ADD_EMPLOYEE_LIST_SUCCESS: 'ADD_EMPLOYEE_LIST_SUCCESS',
	ADD_EMPLOYEE_LIST_FAILED: 'ADD_EMPLOYEE_LIST_FAILED',
	UPDATE_EMPLOYEE_BEGIN: 'UPDATE_EMPLOYEE_BEGIN',
	UPDATE_EMPLOYEE_SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS',
	UPDATE_EMPLOYEE_FAILED: 'UPDATE_EMPLOYEE_FAILED',
	DELETE_EMPLOYEE_BEGIN: 'DELETE_EMPLOYEE_BEGIN',
	DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
	DELETE_EMPLOYEE_FAILED: 'DELETE_EMPLOYEE_FAILED',
};
