export const ActionType = {
	FETCH_EMPLOYEE_LIST_BEGIN: 'FETCH_EMPLOYEE_LIST_BEGIN',
	FETCH_EMPLOYEE_LIST_SUCCESS: 'FETCH_EMPLOYEE_LIST_SUCCESS',
	FETCH_EMPLOYEE_LIST_FAILED: 'FETCH_EMPLOYEE_LIST_FAILED',
};
